apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-scoring-api
  namespace: credit-scoring-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-scoring-api
  template:
    metadata:
      labels:
        app: credit-scoring-api
    spec:
      containers:
      - name: api
        image: cr.yandex/crpn72dh0c06a6o5php2/credit-scoring-api:TAG
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: credit-scoring-service
  namespace: credit-scoring-staging
spec:
  selector:
    app: credit-scoring-api
  ports:
  - port: 80
    targetPort: 8000
